name: Commitlint

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6.2.1
