name: mypy

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.13"
          cache-dependency-glob: "uv.lock"
      - run:
          uv run mypy container_info_mqtt ffmpeg_snapshotter frigate_compressor
          haos_configurator intel_gpu_top_mqtt system_resource_tuner
          turbostat_mqtt
